ProjetoNoticiaV1/Models/Noticia.cs
using System;
using System.Collections.Generic;

namespace ProjetoNoticiaV1.Models;

public partial class Noticia
{
    public int Id { get; set; }

    public string Texto { get; set; } = null!;

    public int UsuarioId { get; set; }

    public string Titulo { get; set; } = null!;

    public virtual ICollection<NoticiaTag>? NoticiaTags { get; set; } = new List<NoticiaTag>();

    public virtual Usuario Usuario { get; set; } = null!;
}

ProjetoNoticiaV1/Controllers/NoticiaController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text.Json.Nodes;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;
using ProjetoNoticiaV1;
using ProjetoNoticiaV1.DTO;
using ProjetoNoticiaV1.Interface;
using ProjetoNoticiaV1.Models;

namespace ProjetoNoticiaV1.Controllers
{
    public class NoticiaController : Controller
    {
        private readonly DbNoticiaContext _context;
        private readonly INoticia _Noticia;

        public NoticiaController(DbNoticiaContext context, INoticia noticia)
        {
            _context = context;
            _Noticia = noticia;
        }

        // GET: Noticia
        public async Task<IActionResult> Index()
        {
            var dbNoticiaContext = _context.Noticia.Include(n => n.Usuario);
            return View(await dbNoticiaContext.ToListAsync());
        }

        public async Task<IActionResult> getNoticias()
        {
            return PartialView(await _Noticia.GetNoticia());
        }

        // GET: Noticia/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var noticia = await _context.Noticia
                .Include(n => n.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (noticia == null)
            {
                return NotFound();
            }

            return View(noticia);
        }

        // GET: Noticia/Create
        public IActionResult Create()
        {
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id");

            //var model = new NoticiaDTO(); 

            return PartialView();
        }

        // POST: Noticia/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NoticiaDTO noticia)
        {
            ModelState.Remove("NoticiaTags");
            ModelState.Remove("NoticiaTagsDisponivel");
            ModelState.Remove("tagId");

            if (ModelState.IsValid)
            {
                await _Noticia.salvarNoticiaAsync(noticia);
                return RedirectToAction(nameof(Index));
            }
            //ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", noticia.UsuarioId);
            return View(noticia);
        }

        // GET: Noticia/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var noticia = await _Noticia.GetNoticiaById(Convert.ToInt32(id));
            if (noticia == null)
            {
                return NotFound();
            }
            //ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", noticia.UsuarioId);
            return View(noticia);
        }

        // POST: Noticia/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NoticiaDTO noticia)
        {
            if (id != noticia.Id)
            {
                return NotFound();
            }

            ModelState.Remove("tagId");

            if (ModelState.IsValid)
            {
                try
                {
                    await _Noticia.salvarNoticiaAsync(noticia);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoticiaExists(noticia.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(noticia);
        }

        // GET: Noticia/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var noticia = await _context.Noticia
                .Include(n => n.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (noticia == null)
            {
                return NotFound();
            }

            return View(noticia);
        }

        // POST: Noticia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var noticia = await _context.Noticia.FindAsync(id);
            if (noticia != null)
            {
                _Noticia.DeleteNoticiaById(id);
            }

            return RedirectToAction(nameof(Index));
        }

        private bool NoticiaExists(int id)
        {
            return _context.Noticia.Any(e => e.Id == id);
        }

        public async Task<JsonResult> ListaTags()
        {
            return Json(await _context.Tags.ToArrayAsync());
        }

        [HttpPost]
        public async Task<IActionResult> _TagsDisponiveis(NoticiaDTO model)
        {
            List<TagDTO> tagDto = new List<TagDTO>();
            foreach (var item in await _context.Tags.ToListAsync())
            {
                tagDto.Add(new TagDTO() { Id = item.Id, Descricao = item.Descricao });
            }
            model.NoticiaTagsDisponivel.Clear();

            var tagDisponivel = tagDto.Where(ms => !model.NoticiaTags.Any(p => p.Id == ms.Id)).ToList();

            if (tagDisponivel != null && tagDisponivel.Count > 0)
                model.NoticiaTagsDisponivel.AddRange(tagDisponivel);

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AdicionaOuRemoveTagNoticia([Bind("NoticiaTags,NoticiaTagsDisponivel,tagId")] NoticiaDTO model)
        {
            try
            {
                if (!String.IsNullOrEmpty(model.tagId))
                    if (model.NoticiaTags.FirstOrDefault(s => s.Id == Convert.ToInt32(model.tagId)) != null)
                        model.NoticiaTags.RemoveAll(s => s.Id == Convert.ToInt32(model.tagId));
                    else
                        model.NoticiaTags.Add(model.NoticiaTagsDisponivel.FirstOrDefault(s => s.Id == Convert.ToInt32(model.tagId)));

                return PartialView("_TagsAdicionadas", model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public async Task<IActionResult> pageEdit(string id)
        {
            if (!String.IsNullOrEmpty(id))
                return View(new NoticiaDTO() { Id = Convert.ToInt32(id) });
            else
                return View(new NoticiaDTO());
        }
    }
}

ProjetoNoticiaV1/Views/Noticia/Create.cshtml
@model ProjetoNoticiaV1.DTO.NoticiaDTO

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Noticia</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" id="formNoticia">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => m.tagId)

            <div class="col-md-12" style="display:flex">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Titulo" class="control-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Texto" class="control-label"></label>
                        <textarea asp-for="Texto" class="form-control"></textarea>
                        <span asp-validation-for="Texto" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6" style="display:flex">
                    <div class="col-md-5" style="margin-left: 30px;">
                        <p>Adicionada</p>
                        <div id="tagAdicionada">
                            @Html.EditorFor(Model => Model.NoticiaTags)
                        </div>
                    </div>
                    <div class="col-md-5" style="margin-left: 30px;">
                        <p>Disponivel</p>
                        <div id="tagDisponivel">
                            @Html.EditorFor(Model => Model.NoticiaTagsDisponivel)
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script type="text/javascript">
        $(document).ready(function () {
            tagDisponivel();
        });

    </script>
}

ProjetoNoticiaV1/Views/Noticia/Delete.cshtml
@model ProjetoNoticiaV1.Models.Noticia

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Noticia</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Texto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Texto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjetoNoticiaV1/Views/Noticia/Details.cshtml
@model ProjetoNoticiaV1.Models.Noticia

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Noticia</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Texto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Texto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjetoNoticiaV1/Views/Noticia/Edit.cshtml
@model ProjetoNoticiaV1.DTO.NoticiaDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Noticia</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" id="formNoticia">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            @Html.HiddenFor(m => m.tagId)

            <div class="col-md-12" style="display:flex">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Titulo" class="control-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Texto" class="control-label"></label>
                        <textarea asp-for="Texto" class="form-control"></textarea>
                        <span asp-validation-for="Texto" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6" style="display:flex">
                    <div class="col-md-5" style="margin-left: 30px;">
                        <p>Adicionada</p>
                        <div id="tagAdicionada">
                            @Html.EditorFor(Model => Model.NoticiaTags)
                        </div>
                    </div>
                    <div class="col-md-5" style="margin-left: 30px;">
                        <p>Disponivel</p>
                        <div id="tagDisponivel">
                            @Html.EditorFor(Model => Model.NoticiaTagsDisponivel)
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
    <script type="text/javascript">
; 
        $(document).ready(function () {
            tagDisponivel();
        });
    </script>
}

ProjetoNoticiaV1/Views/Noticia/Index.cshtml
@model IEnumerable<ProjetoNoticiaV1.Models.Noticia>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Texto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Texto)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {


}

ProjetoNoticiaV1/Views/Noticia/_TagsAdicionadas.cshtml
@model ProjetoNoticiaV1.DTO.NoticiaDTO
@Html.EditorFor(model => model.NoticiaTags)

ProjetoNoticiaV1/Views/Noticia/_TagsDisponiveis.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = null;
}
@model ProjetoNoticiaV1.DTO.NoticiaDTO
@Html.EditorFor(model => model.NoticiaTagsDisponivel)

ProjetoNoticiaV1/Views/Noticia/getNoticias.cshtml
 @model IEnumerable<ProjetoNoticiaV1.DTO.NoticiaDTO>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Texto)
            </th>
            <th>
                Tags
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Texto)
                </td>
                <td>
                    @foreach (var tag in item.NoticiaTags)
                    {
                        <div>
                            @Html.DisplayFor(modelItem => tag.Descricao)
                        </div>

                    }
                </td>
            </tr>
        }
    </tbody>
</table>

ProjetoNoticiaV1/Views/Noticia/pageEdit.cshtml
@model ProjetoNoticiaV1.DTO.NoticiaDTO
 
@Html.HiddenFor(m => m.Id)
<div id="edit">
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            getEdit($('#Id').val());
            tagDisponivel();
            function getEdit(idEdit) {
                 
                $.ajax({
                    async: true,
                    type: 'GET',
                    url: ' @Url.Action("Edit", "Noticia")?id=' + idEdit + '',
                    success: function (response) {
                        $("#edit").html(response);
                    }
                });
            }
        });
    </script>
}